export const BoardData = [
  {
    id: 1,
    createdBy: 'Samppa Nori',
    title: '제목1',
    content: '내용 1',
    createdAt: '2022/01/01',
    role: 'Member',
    deleted: 'false',
    viewCount: 1,
  },
  {
    id: 2,
    createdBy: 'Estavan Lykos',
    title: '제목2',
    content: '내용 2',
    createdAt: '2022/02/07',
    role: 'Staff',
    deleted: 'false',
    viewCount: 1,
  },
  {
    id: 3,
    createdBy: 'Chetan Mohamed',
    title: '제목3',
    content: '내용 3',
    createdAt: '2022/02/07',
    role: 'Admin',
    deleted: 'false',
    viewCount: 1,
  },
  {
    id: 4,
    createdBy: 'Derick Maximinus',
    title: '제목4',
    content: '내용 4',
    createdAt: '2022/03/19',
    role: 'Member',
    deleted: 'true',
    viewCount: 1,
  },
  {
    id: 5,
    createdBy: 'Friderik Dávid',
    title: '제목5',
    content: '내용 5',
    createdAt: '2022/01/21',
    role: 'Staff',
    deleted: 'true',
    viewCount: 1,
  },
  {
    id: 6,
    createdBy: 'Yiorgos Avraamu',
    title: '제목6',
    content: '내용 6',
    createdAt: '2022/01/01',
    role: 'Member',
    deleted: 'true',
    viewCount: 1,
  },
];
