export const BoardData = [
  {
    id: 1,
    author: 'Samppa Nori',
    title: '제목1',
    content: '내용 1',
    avatar: '1.jpg',
    registered: '2022/01/01',
    role: 'Member',
    deleted: 'false',
  },
  {
    id: 2,
    author: 'Estavan Lykos',
    title: '제목2',
    content: '내용 2',
    avatar: '2.jpg',
    registered: '2022/02/07',
    role: 'Staff',
    deleted: 'false',
  },
  {
    id: 3,
    author: 'Chetan Mohamed',
    title: '제목3',
    content: '내용 3',
    avatar: '3.jpg',
    registered: '2022/02/07',
    role: 'Admin',
    deleted: 'false',
  },
  {
    id: 4,
    author: 'Derick Maximinus',
    title: '제목4',
    content: '내용 4',
    avatar: '4.jpg',
    registered: '2022/03/19',
    role: 'Member',
    deleted: 'true',
  },
  {
    id: 5,
    author: 'Friderik Dávid',
    title: '제목5',
    content: '내용 5',

    avatar: '5.jpg',
    registered: '2022/01/21',
    role: 'Staff',
    deleted: 'true',
  },
  {
    id: 6,
    author: 'Yiorgos Avraamu',
    title: '제목6',
    content: '내용 6',
    avatar: '6.jpg',
    registered: '2022/01/01',
    role: 'Member',
    deleted: 'true',
  },
];
